"""Generate radical_dict.json from chaizi-jt.txt."""
with open("chaizi-jt.txt", encoding="utf-8") as f:
    lines = f.readlines()
    character_list = [line.strip().split("\t") for line in lines]
    radical_map: dict[str, list[str]] = {}
    for character, *methods in character_list:
        for METHOD in methods:
            METHOD = "".join(METHOD.split())
            radical_map.setdefault(character, []).append(METHOD)

with open("__init__.py", "w", encoding="utf-8") as f:
    f.write('"""Auto-generated by generate_dict.py."""\n')
    f.write("# pylint: skip-file\n")
    f.write("# mypy: ignore-errors\n")
    f.write("# fmt: off\n")
    f.write("\n")
    f.write(f"RADICAL_MAP: dict[str, list[str]] = {radical_map}\n")
